### what is the diff. btw 2D array and 3D array

2D array is an array that has 1-D array as its elements. 
While 3D array is an array that has 2-D array as ita elements.

In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[2])
print(arr[0,2])
print(arr[0])

[7 8 9]
3
[1 2 3]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.ndim)

2


In [31]:
import numpy as np

arr = np.array([[7, 8, 9], [4, 3, 2], [1, 2, 3]])

print(arr[1])
print(arr[1,0])
print(arr[2])

[4 3 2]
4
[1 2 3]


# Assignment on string

In [2]:
S = 'YES,today is her NIKKAH'

In [45]:
S.count('')

24

In [46]:
S.encode()

b'YES,today is her NIKKAH'

In [50]:
S.endswith('')

True

In [54]:
S.expandtabs(100)

'YES,today is her NIKKAH'

In [61]:
S.find('50')

-1

In [68]:
S.format(2)

'YES,today is her NIKKAH'

In [71]:
S.format_map('')

'YES,today is her NIKKAH'

In [75]:
S.index('')

0

In [2]:
S.isalnum()

False

In [3]:
S.isalpha()

False

In [4]:
S.isascii()

True

In [5]:
S.isdecimal()

False

In [6]:
S.isdigit()

False

In [7]:
S.isidentifier()

False

In [8]:
S.islower()

False

In [9]:
S.isnumeric()

False

In [10]:
S.isprintable()

True

In [11]:
S.isspace()

False

In [12]:
S.istitle()

False

In [13]:
S.isupper()

False

In [25]:
S.join('10')

'1YES,today is her NIKKAH0'

In [21]:
S.ljust(0)

'YES,today is her NIKKAH'

In [26]:
S.lower()

'yes,today is her nikkah'

In [27]:
S.lstrip()

'YES,today is her NIKKAH'

In [5]:
S.maketrans('d')

TypeError: if you give only one argument to maketrans it must be a dict

In [38]:
S.partition('10')

('YES,today is her NIKKAH', '', '')

In [45]:
S.replace()

TypeError: replace() takes at least 2 arguments (1 given)

In [48]:
S.rfind('50')

-1

In [53]:
S.rindex('N')

17

In [62]:
S.rjust(50)

'                           YES,today is her NIKKAH'

In [64]:
S.rpartition('1')

('', '', 'YES,today is her NIKKAH')

In [65]:
S.rsplit()

['YES,today', 'is', 'her', 'NIKKAH']

In [66]:
S.rstrip()

'YES,today is her NIKKAH'

In [68]:
S.split()

['YES,today', 'is', 'her', 'NIKKAH']

In [69]:
S.splitlines()

['YES,today is her NIKKAH']

In [72]:
S.startswith('')

True

In [73]:
S.strip()

'YES,today is her NIKKAH'

In [74]:
S.swapcase()

'yes,TODAY IS HER nikkah'

In [75]:
S.title()

'Yes,Today Is Her Nikkah'

In [78]:
S.translate('')

'YES,today is her NIKKAH'

In [79]:
S.upper()

'YES,TODAY IS HER NIKKAH'

In [81]:
S.zfill(10)

'YES,today is her NIKKAH'